defaults: ../../distillation_math.yaml
distillation:
  num_prompts_per_step: 64
  max_num_steps: 500
  val_batch_size: 32
  val_period: 50
  max_val_samples: 256
checkpointing:
  checkpoint_dir: checkpoints/distillation-qwen3-32b-to-4b-base-long
  save_period: 50
policy:
  model_name: Qwen/Qwen3-4B-Base
  train_global_batch_size: 32
  generation_batch_size: 32
  max_total_sequence_length: 32768
  dynamic_batching:
    enabled: false
  make_sequence_length_divisible_by: 2
  optimizer:
    kwargs:
      lr: 1.0e-05
  scheduler:
  - name: torch.optim.lr_scheduler.LinearLR
    kwargs:
      start_factor: 0.1
      end_factor: 1.0
      total_iters: 100
  - name: torch.optim.lr_scheduler.CosineAnnealingLR
    kwargs:
      T_max: 900
      eta_min: 1.0e-07
  - milestones:
    - 100
teacher:
  model_name: Qwen/Qwen3-32B
  train_global_batch_size: 32
  generation_batch_size: 32
  max_total_sequence_length: 32768
  dynamic_batching:
    enabled: false
  make_sequence_length_divisible_by: 2
  optimizer:
    kwargs:
      lr: 1.0e-05
  scheduler:
  - name: torch.optim.lr_scheduler.LinearLR
    kwargs:
      start_factor: 0.1
      end_factor: 1.0
      total_iters: 100
  - name: torch.optim.lr_scheduler.CosineAnnealingLR
    kwargs:
      T_max: 900
      eta_min: 1.0e-07
  - milestones:
    - 100
logger:
  log_dir: logs/distillation-qwen3-32b-to-4b-base-long
  wandb:
    project: nemo-rl
    name: distillation-qwen3-32b-to-4b-base-long
cluster:
  num_nodes: 2
