defaults: ../../dpo.yaml
dpo:
  max_num_epochs: 2
  max_num_steps: 20
  val_period: 50
  val_batches: 16
  val_global_batch_size: 32
  val_at_start: false
  sft_loss_weight: 0.01
checkpointing:
  save_period: 10000
policy:
  model_name: meta-llama/Llama-3.1-8B-Instruct
  tokenizer:
    name: ${policy.model_name}
  train_global_batch_size: 256
  train_micro_batch_size: 1
  max_total_sequence_length: 2048
  dtensor_cfg:
    tensor_parallel_size: 2
  optimizer:
    kwargs:
      eps: 1.0e-08
  scheduler:
  - name: torch.optim.lr_scheduler.LinearLR
    kwargs:
      start_factor: 1.0e-09
      end_factor: 1.0
      total_iters: 1
  - name: torch.optim.lr_scheduler.ConstantLR
    kwargs:
      factor: 1.0
      total_iters: 10000000000
  - milestones:
    - 1
logger:
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: dpo-llama3.1-8b-instruct-4n8g-fsdp2tp1
cluster:
  gpus_per_node: 8
  num_nodes: 4
