defaults: ../../dpo.yaml
dpo:
  max_num_steps: 20
  val_period: 50
  val_batches: 16
  val_global_batch_size: 32
  val_at_start: false
  sft_loss_weight: 0.01
checkpointing:
  enabled: false
  save_period: 10000
policy:
  model_name: meta-llama/Llama-3.1-8B-Instruct
  tokenizer:
    name: ${policy.model_name}
  train_global_batch_size: 256
  train_micro_batch_size: 1
  max_total_sequence_length: 2048
  dtensor_cfg:
    enabled: false
  make_sequence_length_divisible_by: ${policy.megatron_cfg.tensor_model_parallel_size}
  optimizer: null
  megatron_cfg:
    enabled: true
    pipeline_model_parallel_size: 2
logger:
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: dpo-llama3.1-8b-instruct-4n8g-megatrontp2pp2-quick
cluster:
  gpus_per_node: 8
  num_nodes: 4
