defaults:
  - ../../grpo_math_1B.yaml
  - grpo-deepscaler-1.5b-8K.yaml
loss_fn:
  reference_policy_kl_penalty: 0.0001
  ratio_clip_max: 0.28
policy:
  max_total_sequence_length: 24576
  logprob_batch_size: 2
  dtensor_cfg:
    cpu_offload: true
    sequence_parallel: true
    activation_checkpointing: true
    tensor_parallel_size: 2
    _v2: false
  sequence_packing:
    enabled: false
  optimizer:
    kwargs:
      lr: 5.0e-07
  generation:
    vllm_cfg:
      gpu_memory_utilization: 0.8
      enforce_eager: true
