defaults: ../../grpo_math_1B.yaml
grpo:
  max_num_steps: 450
checkpointing:
  checkpoint_dir: results/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1
policy:
  model_name: Qwen/Qwen2.5-Math-1.5B-Instruct
  tokenizer:
    name: Qwen/Qwen2.5-Math-1.5B-Instruct
  dynamic_batching:
    enabled: true
  sequence_packing:
    enabled: false
  make_sequence_length_divisible_by: 1
  generation:
    max_new_tokens: 512
    stop_token_ids:
    - 151645
    vllm_cfg:
      max_model_len: 512
data:
  max_input_seq_length: 512
logger:
  log_dir: logs/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1
cluster:
  gpus_per_node: 8
