defaults: ../../sft.yaml
sft:
  max_num_steps: 10000
  val_period: 500
  val_batches: 4
  val_global_batch_size: 128
  val_micro_batch_size: 2
  val_at_start: false
checkpointing:
  checkpoint_dir: results/sft-llama3.1-8b-instruct-1n8g-fsdp2tp1-long
  save_period: 100
policy:
  model_name: meta-llama/Llama-3.1-8B
  tokenizer:
    name: meta-llama/Llama-3.1-8B-Instruct
    chat_template: default
  train_global_batch_size: 512
  train_micro_batch_size: 2
  max_total_sequence_length: 4096
  make_sequence_length_divisible_by: 1
  optimizer:
    kwargs:
      lr: 2.0e-05
      weight_decay: 0.01
      eps: 1.0e-08
data:
  dataset_name: openmathinstruct2
  prompt_file: examples/prompts/math.txt
  split: train_1M
  add_generation_prompt: true
  output_key: generated_solution
  seed: 42
logger:
  log_dir: logs/sft-llama3.1-8b-instruct-1n8g-fsdp2tp1-long
  wandb:
    project: nemo-rl
    name: sft-llama3.1-8b-instruct-1n8g-fsdp2tp1-long
  tensorboard:
    log_dir: tb_logs-sft-dev-squad
cluster:
  gpus_per_node: 8
