defaults: ../../sft.yaml
sft:
  max_num_steps: 350
  val_period: 500
checkpointing:
  checkpoint_dir: results/sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp
  save_period: 20
policy:
  model_name: meta-llama/Llama-3.1-8B
  tokenizer:
    name: meta-llama/Llama-3.1-8B-Instruct
    chat_template: default
  train_global_batch_size: 512
  train_micro_batch_size: 2
  max_total_sequence_length: 4096
  dtensor_cfg:
    sequence_parallel: true
    tensor_parallel_size: 2
  make_sequence_length_divisible_by: 2
  optimizer:
    kwargs:
      lr: 2.0e-05
      weight_decay: 0.01
      eps: 1.0e-08
data:
  dataset_name: openmathinstruct2
  prompt_file: examples/prompts/math.txt
  split: train_1M
  add_generation_prompt: true
  output_key: generated_solution
  seed: 42
logger:
  log_dir: logs/sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp
  wandb:
    project: nemo-rl
    name: sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp
  tensorboard:
    log_dir: tb_logs-sft-dev-openmathinstruct2
cluster:
  gpus_per_node: 8
