defaults: ../../sft.yaml
sft:
  max_num_steps: 250
  val_period: 500
checkpointing:
  checkpoint_dir: results/sft-llama3.1-8b-instruct-1n8g-megatron
  save_period: 50
policy:
  model_name: meta-llama/Llama-3.1-8B
  tokenizer:
    name: meta-llama/Llama-3.1-8B-Instruct
    chat_template: default
  train_global_batch_size: 512
  train_micro_batch_size: 2
  max_total_sequence_length: 4096
  dtensor_cfg:
    enabled: false
  sequence_packing:
    enabled: true
  make_sequence_length_divisible_by: ${policy.megatron_cfg.tensor_model_parallel_size}
  optimizer: null
  megatron_cfg:
    enabled: true
    tensor_model_parallel_size: 2
    pipeline_model_parallel_size: 2
    optimizer:
      lr: 2.0e-05
      min_lr: 1.99999e-05
      weight_decay: 0.01
      bf16: true
    scheduler:
      lr_warmup_init: 1.9999e-65
data:
  dataset_name: openmathinstruct2
  prompt_file: examples/prompts/math.txt
  split: train_1M
  add_generation_prompt: true
  output_key: generated_solution
  seed: 42
logger:
  log_dir: logs/sft-llama3.1-8b-1n8g-megatron
  wandb:
    project: nemo-rl
    name: sft-llama3.1-8b-1n8g-megatron
  tensorboard:
    log_dir: tb_logs-sft-dev-openmathinstruct2
cluster:
  gpus_per_node: 8
